# Generated by Django 4.2.5 on 2023-10-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartFarmSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfid', models.IntegerField(default=92)),
                ('remotepower', models.BooleanField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('light', models.IntegerField()),
                ('soil', models.IntegerField()),
                ('ledpower', models.BooleanField()),
                ('ledstate', models.BooleanField()),
                ('ledtoggle', models.BooleanField()),
                ('ledautotoggle', models.BooleanField()),
                ('ledstarttimevalue', models.IntegerField()),
                ('ledstartminutevalue', models.IntegerField()),
                ('ledendtimevalue', models.IntegerField()),
                ('ledendminutevalue', models.IntegerField()),
                ('waterpumppower', models.BooleanField()),
                ('waterpumpstate', models.BooleanField()),
                ('waterpumptoggle', models.BooleanField()),
                ('waterpumpautotoggle', models.BooleanField()),
                ('waterpumpstarttime', models.IntegerField()),
                ('waterpumprunningtime', models.IntegerField()),
                ('waterlevelvoltage', models.FloatField()),
                ('watertemperature', models.FloatField()),
                ('fanpower', models.BooleanField()),
                ('fanstate', models.BooleanField()),
                ('fantoggle', models.BooleanField()),
                ('fanautotoggle', models.BooleanField()),
                ('fanstarttimevalue', models.IntegerField()),
                ('fanstartminutevalue', models.IntegerField()),
                ('fanendtimevalue', models.IntegerField()),
                ('fanendminutevalue', models.IntegerField()),
                ('doorpower', models.BooleanField()),
                ('doorstate', models.BooleanField()),
                ('doortoggle', models.BooleanField()),
                ('doorautotoggle', models.BooleanField()),
                ('doorstarttimevalue', models.IntegerField()),
                ('doorstartminutevalue', models.IntegerField()),
                ('doorendtimevalue', models.IntegerField()),
                ('doorendminutevalue', models.IntegerField()),
                ('waterlevelwarning', models.TextField()),
                ('watertempwarning', models.TextField()),
                ('tempwarning', models.TextField()),
                ('humwarning', models.TextField()),
                ('soilwarning', models.TextField()),
            ],
        ),
    ]
